spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dungeon_explorer_db
    username: dungeon_explorer
    password: dungeon_explorer_adm
  flyway:
    baseline-on-migrate: true
api:
  security:
    token:
      secret: dungeon_explorer_jwt_secret
