spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
api:
  security:
    token:
      secret: ${JWT_SECRET:any_secret_key}
