ALTER TABLE sheets ADD COLUMN bag_id TEXT;
ALTER TABLE sheets ADD COLUMN attributes_id TEXT;
ALTER TABLE sheets ADD COLUMN skill_id TEXT;
ALTER TABLE sheets ADD COLUMN spell_id TEXT;

ALTER TABLE sheets ADD CONSTRAINT fk_bag FOREIGN KEY (bag_id) REFERENCES sheets(id) ON DELETE CASCADE;
ALTER TABLE sheets ADD CONSTRAINT fk_attributes FOREIGN KEY (attributes_id) REFERENCES attributes(id) ON DELETE CASCADE;
ALTER TABLE sheets ADD CONSTRAINT fk_skill FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE;
ALTER TABLE sheets ADD CONSTRAINT fk_spell FOREIGN KEY (spell_id) REFERENCES spells(id) ON DELETE CASCADE;